<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'ps_accounts.link' shared service.

return $this->services['ps_accounts.link'] = \PrestaShop\Module\PsAccounts\Factory\Link::get();
