<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\Module\PsAccounts\Provider\CartDataProvider' shared service.

return $this->services['PrestaShop\\Module\\PsAccounts\\Provider\\CartDataProvider'] = new \PrestaShop\Module\PsAccounts\Provider\CartDataProvider(${($_ = isset($this->services['PrestaShop\\Module\\PsAccounts\\Repository\\CartRepository']) ? $this->services['PrestaShop\\Module\\PsAccounts\\Repository\\CartRepository'] : $this->load('getCartRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['PrestaShop\\Module\\PsAccounts\\Repository\\CartProductRepository']) ? $this->services['PrestaShop\\Module\\PsAccounts\\Repository\\CartProductRepository'] : $this->load('getCartProductRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['PrestaShop\\Module\\PsAccounts\\Formatter\\ArrayFormatter']) ? $this->services['PrestaShop\\Module\\PsAccounts\\Formatter\\ArrayFormatter'] : ($this->services['PrestaShop\\Module\\PsAccounts\\Formatter\\ArrayFormatter'] = new \PrestaShop\Module\PsAccounts\Formatter\ArrayFormatter())) && false ?: '_'});
