<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\Module\PsAccounts\Service\DeletedObjectsService' shared service.

return $this->services['PrestaShop\\Module\\PsAccounts\\Service\\DeletedObjectsService'] = new \PrestaShop\Module\PsAccounts\Service\DeletedObjectsService(${($_ = isset($this->services['ps_accounts.context']) ? $this->services['ps_accounts.context'] : $this->load('getPsAccounts_ContextService.php')) && false ?: '_'}, ${($_ = isset($this->services['PrestaShop\\Module\\PsAccounts\\Repository\\DeletedObjectsRepository']) ? $this->services['PrestaShop\\Module\\PsAccounts\\Repository\\DeletedObjectsRepository'] : $this->load('getDeletedObjectsRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['PrestaShop\\Module\\PsAccounts\\Service\\ProxyService']) ? $this->services['PrestaShop\\Module\\PsAccounts\\Service\\ProxyService'] : $this->load('getProxyServiceService.php')) && false ?: '_'});
