<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\Module\PsAccounts\Api\EventBusProxyClient' shared service.

return $this->services['PrestaShop\\Module\\PsAccounts\\Api\\EventBusProxyClient'] = new \PrestaShop\Module\PsAccounts\Api\EventBusProxyClient(${($_ = isset($this->services['ps_accounts.link']) ? $this->services['ps_accounts.link'] : $this->load('getPsAccounts_LinkService.php')) && false ?: '_'});
