<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'ps_checkout.accounts.service' shared service.

return $this->services['ps_checkout.accounts.service'] = new \PrestaShop\AccountsAuth\Service\PsAccountsService();
