<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\Module\PsAccounts\Provider\OrderDataProvider' shared service.

return $this->services['PrestaShop\\Module\\PsAccounts\\Provider\\OrderDataProvider'] = new \PrestaShop\Module\PsAccounts\Provider\OrderDataProvider(${($_ = isset($this->services['ps_accounts.context']) ? $this->services['ps_accounts.context'] : $this->load('getPsAccounts_ContextService.php')) && false ?: '_'}, ${($_ = isset($this->services['PrestaShop\\Module\\PsAccounts\\Repository\\OrderRepository']) ? $this->services['PrestaShop\\Module\\PsAccounts\\Repository\\OrderRepository'] : $this->load('getOrderRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['PrestaShop\\Module\\PsAccounts\\Repository\\OrderDetailsRepository']) ? $this->services['PrestaShop\\Module\\PsAccounts\\Repository\\OrderDetailsRepository'] : $this->load('getOrderDetailsRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['PrestaShop\\Module\\PsAccounts\\Formatter\\ArrayFormatter']) ? $this->services['PrestaShop\\Module\\PsAccounts\\Formatter\\ArrayFormatter'] : ($this->services['PrestaShop\\Module\\PsAccounts\\Formatter\\ArrayFormatter'] = new \PrestaShop\Module\PsAccounts\Formatter\ArrayFormatter())) && false ?: '_'});
