<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'ps_checkout.logger.sentry.processor' shared service.

return $this->services['ps_checkout.logger.sentry.processor'] = new \PrestaShop\Module\PrestashopCheckout\Sentry\SentryProcessor(${($_ = isset($this->services['ps_checkout.repository.prestashop.account']) ? $this->services['ps_checkout.repository.prestashop.account'] : $this->load('getPsCheckout_Repository_Prestashop_AccountService.php')) && false ?: '_'});
