<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\Module\PsAccounts\Service\SynchronizationService' shared service.

return $this->services['PrestaShop\\Module\\PsAccounts\\Service\\SynchronizationService'] = new \PrestaShop\Module\PsAccounts\Service\SynchronizationService(${($_ = isset($this->services['PrestaShop\\Module\\PsAccounts\\Repository\\AccountsSyncRepository']) ? $this->services['PrestaShop\\Module\\PsAccounts\\Repository\\AccountsSyncRepository'] : $this->load('getAccountsSyncRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['PrestaShop\\Module\\PsAccounts\\Repository\\IncrementalSyncRepository']) ? $this->services['PrestaShop\\Module\\PsAccounts\\Repository\\IncrementalSyncRepository'] : $this->load('getIncrementalSyncRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['PrestaShop\\Module\\PsAccounts\\Service\\ProxyService']) ? $this->services['PrestaShop\\Module\\PsAccounts\\Service\\ProxyService'] : $this->load('getProxyServiceService.php')) && false ?: '_'});
