<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\Module\PsAccounts\Service\ApiAuthorizationService' shared service.

return $this->services['PrestaShop\\Module\\PsAccounts\\Service\\ApiAuthorizationService'] = new \PrestaShop\Module\PsAccounts\Service\ApiAuthorizationService(${($_ = isset($this->services['PrestaShop\\Module\\PsAccounts\\Repository\\AccountsSyncRepository']) ? $this->services['PrestaShop\\Module\\PsAccounts\\Repository\\AccountsSyncRepository'] : $this->load('getAccountsSyncRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['PrestaShop\\Module\\PsAccounts\\Api\\EventBusSyncClient']) ? $this->services['PrestaShop\\Module\\PsAccounts\\Api\\EventBusSyncClient'] : $this->load('getEventBusSyncClientService.php')) && false ?: '_'});
