<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerE52ty3n\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerE52ty3n/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerE52ty3n.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerE52ty3n\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerE52ty3n\appProdProjectContainer([
    'container.build_hash' => 'E52ty3n',
    'container.build_id' => '3dde9343',
    'container.build_time' => 1624390734,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerE52ty3n');
