<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNbnxzvd\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNbnxzvd/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerNbnxzvd.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerNbnxzvd\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerNbnxzvd\appProdProjectContainer([
    'container.build_hash' => 'Nbnxzvd',
    'container.build_id' => '334bd522',
    'container.build_time' => 1623862445,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNbnxzvd');
