<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9dwnu08\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9dwnu08/appProdProjectContainer.php') {
    touch(__DIR__.'/Container9dwnu08.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container9dwnu08\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container9dwnu08\appProdProjectContainer([
    'container.build_hash' => '9dwnu08',
    'container.build_id' => 'c0e4d954',
    'container.build_time' => 1619257293,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9dwnu08');
