<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\Module\PsAccounts\Service\CompressionService' shared service.

return $this->services['PrestaShop\\Module\\PsAccounts\\Service\\CompressionService'] = new \PrestaShop\Module\PsAccounts\Service\CompressionService(${($_ = isset($this->services['PrestaShop\\Module\\PsAccounts\\Formatter\\JsonFormatter']) ? $this->services['PrestaShop\\Module\\PsAccounts\\Formatter\\JsonFormatter'] : ($this->services['PrestaShop\\Module\\PsAccounts\\Formatter\\JsonFormatter'] = new \PrestaShop\Module\PsAccounts\Formatter\JsonFormatter())) && false ?: '_'});
