<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\Module\PsAccounts\Provider\CategoryDataProvider' shared service.

return $this->services['PrestaShop\\Module\\PsAccounts\\Provider\\CategoryDataProvider'] = new \PrestaShop\Module\PsAccounts\Provider\CategoryDataProvider(${($_ = isset($this->services['PrestaShop\\Module\\PsAccounts\\Repository\\CategoryRepository']) ? $this->services['PrestaShop\\Module\\PsAccounts\\Repository\\CategoryRepository'] : $this->load('getCategoryRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['PrestaShop\\Module\\PsAccounts\\Decorator\\CategoryDecorator']) ? $this->services['PrestaShop\\Module\\PsAccounts\\Decorator\\CategoryDecorator'] : ($this->services['PrestaShop\\Module\\PsAccounts\\Decorator\\CategoryDecorator'] = new \PrestaShop\Module\PsAccounts\Decorator\CategoryDecorator())) && false ?: '_'}, ${($_ = isset($this->services['PrestaShop\\Module\\PsAccounts\\Formatter\\ArrayFormatter']) ? $this->services['PrestaShop\\Module\\PsAccounts\\Formatter\\ArrayFormatter'] : ($this->services['PrestaShop\\Module\\PsAccounts\\Formatter\\ArrayFormatter'] = new \PrestaShop\Module\PsAccounts\Formatter\ArrayFormatter())) && false ?: '_'});
