<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\Module\PsAccounts\Provider\GoogleTaxonomyDataProvider' shared service.

return $this->services['PrestaShop\\Module\\PsAccounts\\Provider\\GoogleTaxonomyDataProvider'] = new \PrestaShop\Module\PsAccounts\Provider\GoogleTaxonomyDataProvider(${($_ = isset($this->services['PrestaShop\\Module\\PsAccounts\\Repository\\GoogleTaxonomyRepository']) ? $this->services['PrestaShop\\Module\\PsAccounts\\Repository\\GoogleTaxonomyRepository'] : $this->load('getGoogleTaxonomyRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['ps_accounts.context']) ? $this->services['ps_accounts.context'] : $this->load('getPsAccounts_ContextService.php')) && false ?: '_'});
