<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'ps_checkout.logger.sentry.handler' shared service.

return $this->services['ps_checkout.logger.sentry.handler'] = new \PrestaShop\Module\PrestashopCheckout\Sentry\SentryHandler(${($_ = isset($this->services['ps_checkout.env.sentry']) ? $this->services['ps_checkout.env.sentry'] : ($this->services['ps_checkout.env.sentry'] = new \PrestaShop\Module\PrestashopCheckout\Environment\SentryEnv())) && false ?: '_'});
