<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMenc94x\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMenc94x/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerMenc94x.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerMenc94x\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerMenc94x\appDevDebugProjectContainer([
    'container.build_hash' => 'Menc94x',
    'container.build_id' => '54a9c1df',
    'container.build_time' => 1622195448,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMenc94x');
