# This is a basic workflow to help you get started with Actions

name: Create Zip and upload zip via FTP then unzip

# Controls when the workflow will run
on: 
  push:
    branches:
      - development1

# A workflow run is made up of one or more jobs that can run sequentially or in parallel     
jobs:
  #This workflow has two jobs, zip and upload
  zip:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'release.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'

  upload:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:    
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
            protocol: ftp
            server-dir: ./prestaoperative_CI/
            server: ${{ secrets.FTP_IP }}
            username: ${{ secrets.FTP_USERNAME }}
            password: ${{ secrets.FTP_PASSWORD }}
            exclude:
              - **/modules/**
